"""MK10-PRO package surface witness primitives."""

from __future__ import annotations

import hashlib
import json
import platform
import re
import sys
from importlib import metadata
from importlib import resources
from pathlib import Path
from typing import Any


PACKAGE_NAME = "mk10-pro"
CLAIM = "deterministic_pre_delivery_truth_infrastructure"

DOES_NOT_VERIFY = [
    "playback",
    "device compatibility",
    "venue certification",
    "operator trustworthiness",
    "post-delivery behavior",
    "business outcome",
]

VERIFIES = [
    "bounded evidence shape",
    "package resource presence",
    "policy/schema availability",
    "local proof surface coherence",
    "witness packet generation",
]


def source_root() -> Path:
    return Path(__file__).resolve().parents[1]


def read_source_metadata() -> tuple[str | None, str]:
    pyproject = source_root() / "pyproject.toml"
    if not pyproject.exists():
        return None, ""

    text = pyproject.read_text()
    version_match = re.search(r'^version\s*=\s*"([^"]+)"', text, re.MULTILINE)
    license_match = re.search(r'^license\s*=\s*"([^"]+)"', text, re.MULTILINE)

    version = version_match.group(1) if version_match else None
    license_value = license_match.group(1) if license_match else ""

    return version, license_value


def package_metadata() -> tuple[str, str | None, str]:
    try:
        dist = metadata.distribution(PACKAGE_NAME)
        license_value = dist.metadata.get("License-Expression") or dist.metadata.get("License") or ""
        return "installed", dist.version, license_value
    except metadata.PackageNotFoundError:
        version, license_value = read_source_metadata()
        return "source", version, license_value


def resource_hash(package: str, relative: str) -> str | None:
    path = resources.files(package).joinpath(relative)
    if not path.is_file():
        return None
    return hashlib.sha256(path.read_bytes()).hexdigest()


def boundary_payload() -> dict[str, Any]:
    return {
        "claim": CLAIM,
        "verifies": VERIFIES,
        "does_not_verify": DOES_NOT_VERIFY,
        "distribution_boundary": {
            "github_main": "maintained source surface",
            "pypi": "package distribution surface",
            "v1_0_2": "historical package artifact",
            "v1_0_3": "witness release",
        },
    }


def surface_facts() -> dict[str, Any]:
    import engine

    mode, version, license_value = package_metadata()

    resources_payload = {
        "mtb_schema": resource_hash("mtb", "schema/mtb.schema.json"),
        "ingest_schema": resource_hash("mtb", "schema/ingest.schema.json"),
        "evidence_schema": resource_hash("mtb", "schema/evidence.schema.json"),
        "extended_schema": resource_hash("mtb", "schema/mtb.schema.extended.json"),
        "policy_pack": resource_hash("engine", "policy/policy_pack.yaml"),
        "policy_rules": resource_hash("engine", "policy/rules.yaml"),
        "policy_states": resource_hash("engine", "policy/states.yaml"),
        "dcp_rules": resource_hash("engine", "formats/dcp/rules.yaml"),
    }

    return {
        "mode": mode,
        "package": PACKAGE_NAME,
        "version": version,
        "engine_version": engine.__version__,
        "license": license_value,
        "python": sys.version.split()[0],
        "platform": platform.platform(),
        "commands": ["mk10 proof", "mk10 witness", "mk10 boundary"],
        "resources": resources_payload,
        "boundary": boundary_payload(),
    }


def assert_surface(facts: dict[str, Any]) -> None:
    if not facts["version"]:
        raise RuntimeError("version unavailable")

    if facts["version"] != facts["engine_version"]:
        raise RuntimeError("version mismatch")

    if "Apache-2.0" not in facts["license"]:
        raise RuntimeError("license is not Apache-2.0")

    missing = [name for name, digest in facts["resources"].items() if not digest]
    if missing:
        raise RuntimeError("missing resources: " + ", ".join(missing))


def write_witness(out_dir: Path) -> dict[str, Any]:
    facts = surface_facts()
    assert_surface(facts)

    out_dir.mkdir(parents=True, exist_ok=True)

    witness = {
        "format": "MK10-WITNESS",
        "version": facts["version"],
        "surface": facts,
    }

    (out_dir / "MK10-WITNESS.json").write_text(json.dumps(witness, indent=2, sort_keys=True) + "\n")
    (out_dir / "BOUNDARY.json").write_text(json.dumps(boundary_payload(), indent=2, sort_keys=True) + "\n")
    (out_dir / "README.md").write_text(
        "# MK10-PRO Witness Packet\n\n"
        "Generated by `mk10 witness`.\n\n"
        "Files:\n\n"
        "- `MK10-WITNESS.json`: package/source surface proof facts\n"
        "- `BOUNDARY.json`: exact claim and non-claim boundary\n"
    )

    digest = hashlib.sha256((out_dir / "MK10-WITNESS.json").read_bytes()).hexdigest()
    (out_dir / "SHA256SUMS").write_text(f"{digest}  MK10-WITNESS.json\n")

    return {
        "out": str(out_dir),
        "witness_sha256": digest,
        "files": sorted(p.name for p in out_dir.iterdir()),
    }
